#!/bin/bash

# DESCRIPTION
#
# This plugin monitors the number of pending updates in pacman.
#
# WARNINGS
#
# This plugin will issue a warning state whenever any package can be updated.
#
# ENVIRONMENT
#
# This plugin takes no environment values and can be run as any user.
#
# MAGIC MARKERS
#
# #%# family=auto
# #%# capabilities=autoconf

case $1 in
	config)
		cat <<'EOM'
graph_args --base 1000 -l 0
graph_title Pending updates
graph_vlabel updates
graph_draw no
updates.label updates
updates.info Current number of pending updates
updates.warning 0:0
EOM
		exit 0;;

	autoconf)
		hash checkupdates &> /dev/null && echo yes || echo no
		exit 0;;

esac

echo updates.value $(checkupdates | wc -l)
